# server
server:
  port: 8080
# 数据库连接
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/paper_management?useSSL=true
    username: root
    password: 17876253432
    dbcp2:
      initial-size: 5
      min-idle: 2
      max-total: 10
      max-wait-millis: 1000
      cache-state: false
  freemarker:
    suffix: .html
    template-loader-path: /WEB-INF/view/
    charset: UTF-8
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .html
# 配置mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cchl.entity
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
    aggressive-lazy-loading: true




