# server
server:
  port: 8080
# 数据库连接
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/paper_management?useSSL=true
    username: root
    password: 17876253432
    dbcp2:
      initial-size: 5
      min-idle: 2
      max-total: 10
      max-wait-millis: 1000
      cache-state: false
# 配置mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cchl.entity
  configuration:
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
    map-underscore-to-camel-case: true
    aggressive-lazy-loading: false



